const TELAS = {
        TELA_INICIO: 'TELA_INICIO',
        TELA_LOGIN: 'TELA_LOGIN',
        TELA_CADASTRO: 'TELA_CADASTRO',
        TELA_LISTA_PRODUTOS: 'TELA_LISTA_PRODUTOS',
        TELA_NOVO_PRODUTO: 'TELA_NOVO_PRODUTO',
        TELA_EDITAR_PRODUTO: 'TELA_EDITAR_PRODUTO',
        
        TELA_PERFIL_USUARIO: 'TELA_PERFIL_USUARIO',
        TELA_EDITAR_PERFIL: 'TELA_EDITAR_PERFIL'
};

export default TELAS;